# Generated by Django 2.2.3 on 2019-10-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_has_confirmed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CinfirmString',
            new_name='ConfirmString',
        ),
    ]
